"use client";

import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import Navbar from "./_navbar/page";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Provider } from "react-redux";
import { store } from "./_redux/store";
import { Toaster } from "react-hot-toast";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

// export const metadata: Metadata = {
//   title: "Viba",
//   description: "Generated by Abdelrahman Alaa",};
// الميتا هتتعمل بتاج هيد في الhtml عشان دلوقتي دا كلاينت كومبوننت مينفعش تتحط هنا

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body style={{ fontFamily: roboto.style.fontFamily }}>
        <Provider store={store}>
          <AppRouterCacheProvider>
            <Navbar />
            <LocalizationProvider dateAdapter={AdapterDayjs}>
                {children}
                <Toaster />
            </LocalizationProvider>
          </AppRouterCacheProvider>
        </Provider>
      </body>
    </html>
  );
}
